version: "3.7"
services:
  app:
    build:
      context: "."
      target: "dev"
      dockerfile: "./deployments/docker/zero-api/Dockerfile"
    volumes:
      - ".:/app"
      - "/root/go/pkg/mod"
      - "/root/.cache/go-build"
    ports: ["8080:8080"]
    env_file: "./config/local.env"

  mysql:
    image: mysql:8.1.0
    tty: true
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - .:/app
      - ./deployments/docker/mysql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./deployments/docker/mysql/init.sql:/var/tmp/init.sql
      - sql-data:/var/lib/mysql
    ports: ["3306:3306"]
    command: "--explicit-defaults-for-timestamp"

volumes:
  sql-data:
