// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/takumi2786/zero-backend/internal/application/usecase"
	"github.com/takumi2786/zero-backend/internal/interfaces/controller"
	"github.com/takumi2786/zero-backend/internal/interfaces/repository"
	"github.com/takumi2786/zero-backend/internal/util"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeLoginController(cfg *util.Config, logger *zap.Logger, sqlHandler repository.SQLHandler) *controller.LoginController {
	userRepository := repository.NewUserRepository(sqlHandler)
	authUserRepository := repository.NewAuthUserRepository(sqlHandler)
	iTokenGenerator := usecase.NewJWTTokenGenerator()
	iLoginUsecase := usecase.NewLoginUsecase(cfg, logger, userRepository, authUserRepository, iTokenGenerator)
	loginController := controller.NewLoginController(logger, iLoginUsecase)
	return loginController
}
